/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ProcessedContent } from "./ProcessedContent";
import { ProcessedContentCountArgs } from "./ProcessedContentCountArgs";
import { ProcessedContentFindManyArgs } from "./ProcessedContentFindManyArgs";
import { ProcessedContentFindUniqueArgs } from "./ProcessedContentFindUniqueArgs";
import { DeleteProcessedContentArgs } from "./DeleteProcessedContentArgs";
import { ProcessedContentService } from "../processedContent.service";
@graphql.Resolver(() => ProcessedContent)
export class ProcessedContentResolverBase {
  constructor(protected readonly service: ProcessedContentService) {}

  async _processedContentsMeta(
    @graphql.Args() args: ProcessedContentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ProcessedContent])
  async processedContents(
    @graphql.Args() args: ProcessedContentFindManyArgs
  ): Promise<ProcessedContent[]> {
    return this.service.processedContents(args);
  }

  @graphql.Query(() => ProcessedContent, { nullable: true })
  async processedContent(
    @graphql.Args() args: ProcessedContentFindUniqueArgs
  ): Promise<ProcessedContent | null> {
    const result = await this.service.processedContent(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProcessedContent)
  async deleteProcessedContent(
    @graphql.Args() args: DeleteProcessedContentArgs
  ): Promise<ProcessedContent | null> {
    try {
      return await this.service.deleteProcessedContent(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
